# Generated by Django 3.1.3 on 2021-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
