# Generated by Django 3.1.3 on 2021-12-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_content_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='level',
        ),
    ]
