# Generated by Django 3.1.3 on 2022-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_content_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
